### ISSUE TITLE
Should we archive this repo?

### ISSUE THREAD

**Issue by TimothyGu** [nodejs/wiki-archive#1]
GitHub provides the [option](https://help.github.com/articles/about-archiving-repositories/) of archiving repositories so that they become read-only. It seems to me that this repository is a good candidate for that, as we don't expect any changes to be made anymore. (In fact it has "archive" in its name.) It's also different from node-v0.x-archive in that this repo doesn't have any issues to link to (save for this one).

Thoughts?

/cc @nodejs/community-committee @nodejs/documentation @nodejs/tsc

**Comment by Trott** [comment]
Sounds fine to me. Note that according to the [relevant policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories), the procedure for archiving is to open an issue like this one in the `admin` repo.

**Comment by TimothyGu** [comment]
Moved to https://github.com/nodejs/admin/issues/175.
